import { parseDbml } from '../model/dbmlParser';
import { SqlDialect } from '../model/types';

export interface ExportSqlResponse {
  sql: string;
  dialect: SqlDialect;
  fromFallback?: boolean;
}

export interface ImportSqlResponse {
  dbml: string;
  fromFallback?: boolean;
}

/**
 * DBML 스키마를 SQL DDL로 변환 (백엔드 API 호출, 실패 시 클라이언트 폴백)
 */
export async function exportDbmlToSql(
  dbml: string,
  dialect: SqlDialect = 'postgres',
): Promise<ExportSqlResponse> {
  try {
    const res = await fetch('/api/v1/dbml/export-sql', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ dbml, dialect }),
    });

    if (res.ok) {
      const data = await res.json();
      return { sql: data.sql, dialect: data.dialect || dialect };
    }
  } catch {
    // 백엔드 미구현 또는 네트워크 오류 시 클라이언트 폴백으로 진행
  }

  // 클라이언트 사이드 Fallback DDL 생성기
  return {
    sql: generateClientFallbackSql(dbml, dialect),
    dialect,
    fromFallback: true,
  };
}

/**
 * SQL DDL을 DBML 스키마로 역변환 (백엔드 API 호출, 실패 시 클라이언트 폴백)
 */
export async function importSqlToDbml(
  sql: string,
  dialect: SqlDialect = 'postgres',
): Promise<ImportSqlResponse> {
  try {
    const res = await fetch('/api/v1/dbml/import-sql', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sql, dialect }),
    });

    if (res.ok) {
      const data = await res.json();
      return { dbml: data.dbml };
    }
  } catch {
    // 백엔드 미구현 시 클라이언트 폴백
  }

  return {
    dbml: generateClientFallbackDbml(sql),
    fromFallback: true,
  };
}

/**
 * DBML 코드 포맷팅
 */
export async function formatDbmlCode(dbml: string): Promise<string> {
  try {
    const res = await fetch('/api/v1/dbml/format', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ dbml }),
    });

    if (res.ok) {
      const data = await res.json();
      return data.formattedDbml;
    }
  } catch {
    // 폴백
  }

  // 클라이언트 사이드 정리 (앞뒤 공백 정돈)
  return dbml
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n');
}

/**
 * 클라이언트 사이드 자체 기본 SQL DDL 생성기
 */
function generateClientFallbackSql(dbml: string, dialect: SqlDialect): string {
  const schema = parseDbml(dbml);
  if (!schema.isValid || schema.tables.length === 0) {
    return `-- [Notice] 스키마를 올바르게 파싱할 수 없습니다.\n`;
  }

  const quote = dialect === 'mysql' ? '`' : '"';
  const outLines: string[] = [
    `-- Generated by my-space DBML Utility (${dialect})`,
    `-- Engine: client-fallback-v1`,
    '',
  ];

  // 1. CREATE TABLE 구문들
  schema.tables.forEach((table) => {
    outLines.push(`CREATE TABLE ${quote}${table.name}${quote} (`);

    const colDefs: string[] = [];
    table.fields.forEach((field) => {
      let def = `  ${quote}${field.name}${quote} ${field.type.toUpperCase()}`;
      if (field.pk) def += ' PRIMARY KEY';
      if (field.increment) {
        def += dialect === 'postgres' ? '' : dialect === 'mysql' ? ' AUTO_INCREMENT' : ' AUTOINCREMENT';
      }
      if (field.unique) def += ' UNIQUE';
      if (field.notNull) def += ' NOT NULL';
      if (field.default !== undefined) {
        def += ` DEFAULT ${field.default}`;
      }
      colDefs.push(def);
    });

    outLines.push(colDefs.join(',\n'));
    outLines.push(');\n');
  });

  // 2. ALTER TABLE ADD FOREIGN KEY 관계 구문들
  if (schema.relationships.length > 0) {
    outLines.push('-- Foreign Key Relationships');
    schema.relationships.forEach((rel) => {
      const constraintName = `fk_${rel.sourceTable}_${rel.sourceColumn}`;
      outLines.push(
        `ALTER TABLE ${quote}${rel.sourceTable}${quote} ADD CONSTRAINT ${quote}${constraintName}${quote} FOREIGN KEY (${quote}${rel.sourceColumn}${quote}) REFERENCES ${quote}${rel.targetTable}${quote} (${quote}${rel.targetColumn}${quote});`,
      );
    });
    outLines.push('');
  }

  return outLines.join('\n');
}

/**
 * 클라이언트 사이드 기본 SQL -> DBML 역변환기 (간단한 CREATE TABLE 파서)
 */
function generateClientFallbackDbml(sql: string): string {
  const tableRegex = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?["`]?([a-zA-Z0-9_]+)["`]?\s*\(([\s\S]*?)\);/gi;
  const dbmlTables: string[] = [];
  let match: RegExpExecArray | null;

  while ((match = tableRegex.exec(sql)) !== null) {
    const tableName = match[1];
    const body = match[2];
    const lines = body.split('\n');
    const fieldLines: string[] = [];

    for (const rawLine of lines) {
      const line = rawLine.trim().replace(/,$/, '');
      if (!line || line.startsWith('--') || /^PRIMARY\s+KEY/i.test(line) || /^CONSTRAINT/i.test(line)) {
        continue;
      }

      const colMatch = line.match(/^["`]?([a-zA-Z0-9_]+)["`]?\s+([a-zA-Z0-9_()]+)(.*)/i);
      if (colMatch) {
        const colName = colMatch[1];
        const colType = colMatch[2].toLowerCase();
        const rest = colMatch[3] || '';
        const tags: string[] = [];

        if (/PRIMARY\s+KEY/i.test(rest)) tags.push('pk');
        if (/UNIQUE/i.test(rest)) tags.push('unique');
        if (/NOT\s+NULL/i.test(rest)) tags.push('not null');

        const tagStr = tags.length > 0 ? ` [${tags.join(', ')}]` : '';
        fieldLines.push(`  ${colName} ${colType}${tagStr}`);
      }
    }

    dbmlTables.push(`Table ${tableName} {\n${fieldLines.join('\n')}\n}`);
  }

  return dbmlTables.length > 0 ? dbmlTables.join('\n\n') + '\n' : '// 변환 가능한 CREATE TABLE 구문을 찾지 못했습니다.\n';
}
